all: main

main: main.o module1.o module2.o
	gcc -o main main.o module1.o module2.o

main.o: main.c module1.h module2.h
	gcc -c main.c

module1.o: module1.c module1.h
	gcc -c module1.c

module2.o: module2.c module2.h
	gcc -c module2.c

clean:
	rm -f *.o main
